version: "3.2" 
services:
    redis:
        image: "redis:alpine"
        container_name: redis
        command: redis-server --requirepass ${REDIS_PASS} --protected-mode ${REDIS_PROTECT}
        ports: 
            - 6379:6379
        volumes: 
            - ${EXPORT_PATH}/redis:/var/lib/redis  
        environment:
            - REDIS_REPLICATION_MODE=master

    mongodb:
        image: mongo
        container_name: mongo
        environment:
            - MONGO_INITDB_DATABASE=$MONGO_DATABASE
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
        volumes: 
            - ${EXPORT_PATH}/mongodb:/data
        ports: 
            - 27017:27017

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ${EXPORT_PATH}/rabbitmq/data/:/var/lib/rabbitmq/
            - ${EXPORT_PATH}/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672


