version: "3.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: web
    container_name: web
    volumes:
      - ./:/src
    expose:
      - "8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    ports:
      - "8001:8001"
    volumes:
      - ./:/src
      - ./logi_web/conf/nginx:/etc/nginx/conf.d